### ISSUE TITLE
it crashes with escaped characters in the strings

### ISSUE THREAD

**Issue by spiderbit** [Junker/stumpwm-rofi#1]
(rofi:menu (list (list "foo\"bar" "bar"))) 

That don't runs, same with "foobar\\"

I use that for window-list and the apps have such characters in the name.

**Comment by Junker** [comment]
Fixed in [#1a14c45fb311d85a77ea0ac42af3ad2d2563f056](https://github.com/Junker/stumpwm-rofi/commit/1a14c45fb311d85a77ea0ac42af3ad2d2563f056)
